name: CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.18.6
      - name: Run checks
        run: make lint test
