name: CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Setup go
        uses: actions/setup-go@v3
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
      - name: Run checks
        run: make lint test integration-test
